### ISSUE TITLE
Update for Statamic V3?

### ISSUE THREAD

**Issue by austriker27** [gridonic/statamic-shopify#2]
Hello,

I'm wondering if there's been any thoughts on updating this for Statamic V3? I'd be curious to try it once its compatible. 

Thanks!

**Comment by rustypaul** [comment]
We're definitely interested in a shopify plugin for v3 too

**Comment by wanze** [comment]
Hi everyone,

First of all, sorry for the late reply. Unfortunately we cannot release a version for Statamic 3. But, as you may know, there is another addon available for v3: https://statamic.com/addons/jack-whiting/shopify

Happy christmas! 🎄
